// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadLsm returns the embedded CollectionSpec for lsm.
func loadLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm: %w", err)
	}

	return spec, err
}

// loadLsmObjects loads lsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmObjects
//	*lsmPrograms
//	*lsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmSpecs struct {
	lsmProgramSpecs
	lsmMapSpecs
}

// lsmSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmProgramSpecs struct {
	Prog *ebpf.ProgramSpec `ebpf:"prog"`
}

// lsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmMapSpecs struct {
	EventRingbuf *ebpf.MapSpec `ebpf:"event_ringbuf"`
}

// lsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmObjects struct {
	lsmPrograms
	lsmMaps
}

func (o *lsmObjects) Close() error {
	return _LsmClose(
		&o.lsmPrograms,
		&o.lsmMaps,
	)
}

// lsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmMaps struct {
	EventRingbuf *ebpf.Map `ebpf:"event_ringbuf"`
}

func (m *lsmMaps) Close() error {
	return _LsmClose(
		m.EventRingbuf,
	)
}

// lsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmPrograms struct {
	Prog *ebpf.Program `ebpf:"prog"`
}

func (p *lsmPrograms) Close() error {
	return _LsmClose(
		p.Prog,
	)
}

func _LsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_bpfeb.o
var _LsmBytes []byte
