name: ci

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        build-type: Release

    - name: Test Project
      uses: threeal/ctest-action@v1.1.0
      with:
        build-config: Release
